// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Prefer publish-time Vite envs; provide safe fallbacks to prevent runtime crashes
const VITE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const VITE_PUBLISHABLE = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;
const VITE_ANON = import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined;
const VITE_PROJECT_ID = import.meta.env.VITE_SUPABASE_PROJECT_ID as string | undefined;

const FALLBACK_PROJECT_ID = 'dbcsygvthzkdujeugzca';
const FALLBACK_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRiY3N5Z3Z0aHprZHVqZXVnemNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI1NzAwOTUsImV4cCI6MjA3ODE0NjA5NX0.cDORDUihudFD2xy1IIny4IEQ-nyH0vKTYLmMRJoIhP0';
const SUPABASE_URL = VITE_URL || `https://${(VITE_PROJECT_ID || FALLBACK_PROJECT_ID)}.supabase.co`;
const SUPABASE_KEY = VITE_PUBLISHABLE || VITE_ANON || FALLBACK_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_KEY) {
  // Surface a clear diagnostic once, instead of a cryptic runtime error
  console.error('[Supabase] Missing configuration', {
    hasUrl: !!SUPABASE_URL,
    hasKey: !!SUPABASE_KEY,
    urlEnv: 'VITE_SUPABASE_URL',
    keyEnvTried: ['VITE_SUPABASE_PUBLISHABLE_KEY', 'VITE_SUPABASE_ANON_KEY']
  });
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL as string, SUPABASE_KEY as string, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});